{{- if eq (include "acceleration-a.isEnabled" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acceleration-a.fullname" . }}
  labels:
    {{- include "acceleration-a.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default "80" }}
      targetPort: {{ .Values.containerPort | default "3002" }}
      protocol: TCP
      name: http
  selector:
    {{- include "acceleration-a.selectorLabels" . | nindent 4 }}
{{- end -}}